### ISSUE TITLE
Set up GitHub check for Drone

### ISSUE THREAD

**Issue by asbjornu** [drone/envsubst#16]
Since envsubst seems to be using [Drone.io](https://drone.io/) for CI, it would be helpful for code contributors (such as myself) if the build status was reported back to GitHub as a [check](https://developer.github.com/v3/checks/). Could you please set something like that up? I can contribute a Travis configuration as well, if that's of interest.

**Comment by JordanSussman** [comment]
Drone itself does not currently support checks since it utilizes [GitHub OAuth Apps](https://developer.github.com/apps/building-oauth-apps/) instead of [GitHub Apps](https://developer.github.com/apps/managing-github-apps/).

https://github.com/drone/drone/issues/2422 talks about adding support for GitHub apps and therefore checks.

**Comment by asbjornu** [comment]
I see. Perhaps another CI provider should be added until Drone has GitHub check support, then?

**Comment by bradrydzewski** [comment]
CI was temporarily disabled because we were migrating from a privately hosted CI instance to a public [cloud.drone.io](https://cloud.drone.io/drone/envsubst) instance.  Drone reports back the status to the Pull Request using the commit status API, and has been enabled at Drone Cloud, so we can consider this issue resolved.
