### ISSUE TITLE
(feature) Allow brace-less substitutions

### ISSUE THREAD

**Issue by mohkale** [drone/envsubst#25]
Brackets are super useful when you want to process a variable while substituting, but when all you want is to substitute a variable, they make things harder to read.

```sh
echo ${foo}
echo $foo
```
It'd nice if this package allowed bracket less substitutions.

**Comment by bradrydzewski** [comment]
👋 hey there, if you need brace-less substitution we recommend using [os.ExpandEnv](https://golang.org/pkg/os/#ExpandEnv).  This library was designed to support docker-compose [1] and drone, which only substitutes variables with curly braces and, by design, ignores variables without curly braces. Since we do not require such functionality in our upstream repositories, this is not something we plan to implement.

[1] https://docs.docker.com/compose/environment-variables/#substitute-environment-variables-in-compose-files

**Comment by mohkale** [comment]
@bradrydzewski The reason I don't want to use `os.ExpandEnv` is that it can only substitute from the current processes environment. This package on the other hand allows substituting from arbitrary sources (including my use case of a map). I appreciate you have no intention to support this. Thanks for this great package :smile:.

**Comment by bradrydzewski** [comment]
Sorry, wrong function, you can use `os.Expand` instead 🙂 

```Go
package main

import "os"

func main() {
	s := "hello ${NAME}"
	p := map[string]string{"NAME": "Jane"}

	s = os.Expand(s, func(k string) string {
		return p[k]
	})

	println(s)
}
```

**Comment by mohkale** [comment]
Ok, wow, thnx that's pretty great. :+1:.

**Comment by UiP9AV6Y** [comment]
sorry for hijacking this issue, but docker-compose actually _does_ [support](https://docs.docker.com/compose/compose-file/#variable-substitution) brace-less variable substitution.

> Both $VARIABLE and ${VARIABLE} syntax are supported. 

is the lack of support for this feature a definitive answer? i do have the use-case where i need to replace brace-less variables *and* variables with substitutions. i suppose i could do a double pass (first  envsubst.Eval followed by os.Expand), but the performance would suffer.

**Comment by tboerger** [comment]
A braceless substitution would potentially break existing Drone definitions as people build on this behavior.
